config/routes.rb
Rails.application.routes.draw do
  get 'flights/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :flights
  resources :bookings

  root "flights#index"

end

app/models/airport.rb
class Airport < ApplicationRecord
    has_many :departing_flights, foreign_key: :departure_airport_id, class_name: 'Flight'
    has_many :arriving_flights, foreign_key: :arrival_airport_id, class_name: 'Flight'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :flight
    has_many :passengers
    accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ApplicationRecord
    belongs_to :departure_airport, class_name: 'Airport'
    belongs_to :arrival_airport, class_name: 'Airport'
    has_many :bookings
    has_many :passengers, through: :bookings

    def departure_date
        departure.strftime("%d/%m/%Y")
    end

end

app/models/passenger.rb
class Passenger < ApplicationRecord
    belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    
    def new
        @booking = Booking.new
        @flight = Flight.find(params[:flight])
        @number_of_passengers = params[:number_of_passengers].to_i
        @number_of_passengers.times { @booking.passengers.build }
    end
    
    def create
        @booking = Booking.new(booking_params)
        
        respond_to do |format|
            if @booking.save
                PassengerMailer.with(booking_id: @booking.id).confirmation_email.deliver_later
                format.html { redirect_to @booking }
            else
                format.html { render :new, status: :unprocessable_entity }
            end
        end
    end

    def show
        @booking = Booking.find(params[:id])
    end

    private

    def booking_params
        params.require(:booking).permit(:flight_id, :number_of_passengers, passengers_attributes: [:name, :email])
    end
    
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    #nothing needed for search bar, url and models already defined in view
    if params[:flight]
      @flight_results = Flight.where(departure_airport_id: flight_params[:departure_airport_id], 
                                      arrival_airport_id: flight_params[:arrival_airport_id]
                                      )
    end

  end



  private

  def search_params
    params.require(:flight).permit(:departure_airport_id, :arrival_airport_id, :departure, :number_of_passengers)
  end

  def flight_params
    params.require(:flight).permit(:departure_airport_id, :arrival_airport_id, :departure, :number_of_passengers)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1> Confirm your details</h1>

<h2>Flight summary:</h2>
<h4>
    <%= @flight.departure_airport.code %> -
    <%= @flight.arrival_airport.code %>
    Departure: <%= @flight.departure %>
    Flight duration:<%= @flight.duration %>
    No. passengers: <%= @number_of_passengers.to_s %>
</h4>

<h2>Passenger details:</h2>

<%= form_with model: @booking, local: true do |booking| %>
     <% x = 1%>
    <%= booking.fields_for :passengers do |passenger| %>
        <%= "Passenger #{x}:" %><br/>
        <%= passenger.label :name %> <br/>
        <%= passenger.text_field :name %><br/>

        <%= passenger.label :email %> <br/>
        <%= passenger.text_field :email %><br/>

         <% x += 1%>
    <% end %>

    <%= booking.hidden_field :number_of_passengers, value: @number_of_passengers%>

    <%= booking.hidden_field :flight_id, value: params[:flight] %>

    <div>
        <%= booking.submit "Confirm & purchase", class: 'book_btn', id: 'book_btn'%>
    </div>
<% end %>

app/views/bookings/show.html.erb
<h1> Your booking </h1>

<h2>Booking ref: 00000 </h2>

<h2>Flight summary:</h2>
<p>
    <%= @booking.flight.departure_airport.code %> -
    <%= @booking.flight.arrival_airport.code %>
    Departure: <%= @booking.flight.departure %>
    Flight duration:<%= @booking.flight.duration %>
</p>

<h2>Passenger details:</h2>
<table>
    <thead>
        <tr>
            <th>Passenger name</th>
            <th>Email</th>
        </tr>
    </thead>
    <tbody>
        <% @booking.passengers.each_with_index do |passenger, index| %>
            <tr>
                <td><%= passenger.name %></td>
                <td><%= passenger.email %></td>
            </tr>
        <% end %>
    </tbody>
</table>
<br/>

<%= link_to "Back to search", root_path %>

app/views/flights/index.html.erb
<h1>Book your flight</h1>

<%= form_with(url: "/flights", method: :get, local: true) do |form| %> <%# url: "/flights" and local means no @ or model need to be defined in controller %>
    
    <%= form.label :departure_airport %><br>
    <%= collection_select(:flight, :departure_airport_id, Airport.all, :id, :code, prompt: true) %><br>
  
    <%= form.label :arrival_airport %><br>
    <%= collection_select(:flight, :arrival_airport_id, Airport.all, :id, :code, prompt: true) %><br>

    <%= form.label :number_of_passengers %><br>
    <%= form.select :number_of_passengers, (1..4) %><br>

    <%= form.label :departure_date %><br>
    <%= collection_select(:flight, :departure, Flight.all, :id, :departure_date, prompt: true) %><br>

    <div>
        <%= form.submit "Search"%>
    </div>
<% end %>

<% if !@flight_results.nil? %>
    <% if @flight_results.any? %>
        <%= form_tag new_booking_path, method: :get do |form|%>

            <% @flight_results.each do |flight| %>
                <%= radio_button_tag(:flight, flight.id, { checked: true }) %>
                <%= flight.departure_airport.code %>
                <%= flight.arrival_airport.code %>
                <%= flight.departure %>
                <%= flight.duration %>
            <% end %>
            
            <%= hidden_field_tag :number_of_passengers, params[:number_of_passengers] %>
            <div>
                <%= submit_tag("Book flight", class: 'book_btn', id: 'book_btn')%>
            </div>
        <% end %>
    <% else %>
        <p> No flights match your criteria </p>
    <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>